### ISSUE TITLE
Search by uicref

### ISSUE THREAD

**Issue by Jxlle** [OpenRailwayMap/OpenRailwayMap-api#1]
Hi,

Is it possible for the api to handle requests that try to find a railway facility by its uicref number?
For example, the station _Leuven_ can be found by its name. The api also returns its uicref number _8833001_, but there seems no possible way to find a facility by that number.

Kind regards

**Comment by Nakaner** [comment]
You can search by uic_ref.

`https://api.openrailwaymap.org/v2/facility?uic_ref=8833001` returns Leuven.
